language: objective-c
os: osx
osx_image: xcode9.2
notifications:
  email: false

xcode_workspace: insights-for-instagram.xcworkspace
podfile: Podfile
cache: cocoapods

before_install:
  - rvm install ruby --latest
  - gem install cocoapods
  - gem install xcpretty -N
  - gem install fastlane --no-ri --no-rdoc --no-document
  - pod repo update master

#  - brew update
#  - brew install swiftlint || true

before_install:
  - gem install fastlane --no-ri --no-rdoc --no-document
jobs:
  include:
    - stage: XCTest
      script:
        - fastlane scan -scheme insights-for-instagram