language: objective-c
os: osx
osx_image: xcode9.2
xcode_workspace: insights-for-instagram.xcworkspace
podfile: Podfile
cache: cocoapods
notifications:
  email: false

before_install:
  - rvm install ruby --latest
  - gem install cocoapods
  - pod repo update master
  - gem install fastlane --no-ri --no-rdoc --no-document

#  - brew update
#  - brew install swiftlint || true

jobs:
  include:
    - stage: XCTest
      script:
        - fastlane scan -s insights-for-instagram